// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOXonanE127b9iqMdJ7mrohX5gEFpgqe4',
    appId: '1:794560851744:web:f9ccc146927659e218f145',
    messagingSenderId: '794560851744',
    projectId: 'ginkaoyang-fb446',
    authDomain: 'ginkaoyang-fb446.firebaseapp.com',
    databaseURL: 'https://ginkaoyang-fb446-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginkaoyang-fb446.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZRV_1xld9YMTcgx4W3pkPAWsRvAbDZ5k',
    appId: '1:794560851744:android:1c884e5f1c03f6ad18f145',
    messagingSenderId: '794560851744',
    projectId: 'ginkaoyang-fb446',
    databaseURL: 'https://ginkaoyang-fb446-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginkaoyang-fb446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQXmk4zohyE5XmhYhlkpBEx--Qdl3zf_8',
    appId: '1:794560851744:ios:30df271123c9348018f145',
    messagingSenderId: '794560851744',
    projectId: 'ginkaoyang-fb446',
    databaseURL: 'https://ginkaoyang-fb446-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginkaoyang-fb446.appspot.com',
    iosBundleId: 'com.example.ginkhaoyang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQXmk4zohyE5XmhYhlkpBEx--Qdl3zf_8',
    appId: '1:794560851744:ios:30df271123c9348018f145',
    messagingSenderId: '794560851744',
    projectId: 'ginkaoyang-fb446',
    databaseURL: 'https://ginkaoyang-fb446-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginkaoyang-fb446.appspot.com',
    iosBundleId: 'com.example.ginkhaoyang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOXonanE127b9iqMdJ7mrohX5gEFpgqe4',
    appId: '1:794560851744:web:9ea321df11b3615918f145',
    messagingSenderId: '794560851744',
    projectId: 'ginkaoyang-fb446',
    authDomain: 'ginkaoyang-fb446.firebaseapp.com',
    databaseURL: 'https://ginkaoyang-fb446-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ginkaoyang-fb446.appspot.com',
  );
}
